In [1]:
# Libraries import
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

print("All libraries load✅")

All libraries load✅


In [2]:
iris = load_iris()

# Features and Labels Separate
X = iris.data    # 4 measurements (input)
y = iris.target  # flowerS Name  (output)

# Dataset ka size dekho
print("Dataset ka size:", X.shape)
print("Total flowers:", len(y))
print("Flower classes:", iris.target_names)

Dataset ka size: (150, 4)
Total flowers: 150
Flower classes: ['setosa' 'versicolor' 'virginica']


In [3]:
# Data 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (120, 4)
Testing data: (30, 4)


In [4]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)


X_test = scaler.transform(X_test)

print("Scaling Done ! ✅")
print("1st 2 rows training data ")
print(X_train[:2])

Scaling Done ! ✅
1st 2 rows training data 
[[-1.47393679  1.20365799 -1.56253475 -1.31260282]
 [-0.13307079  2.99237573 -1.27600637 -1.04563275]]


In [5]:
# KNN Model
model = KNeighborsClassifier(n_neighbors=5)

#  train model on training data
model.fit(X_train, y_train)

print("Model train Done  ✅")

# prediction on test data
predictions = model.predict(X_test)

print("Predictions:", predictions)
print("Actual:     ", y_test)

Model train Done  ✅
Predictions: [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Actual:      [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [6]:
# Confusion Matrix
cm = confusion_matrix(y_test, predictions)
print("Confusion Matrix:")
print(cm)

print("\n")

# Classification Report
report = classification_report(y_test, predictions,
                               target_names=iris.target_names)
print("Classification Report:")
print(report)

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

